version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tourplanner-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: edin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: tourplanner
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: